server:
  port: 6039
  servlet:
    context-path: /

spring:
  application:
    name: spring-ai-alibaba-copilot
  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai_copilot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      # 提供一个临时的API key来避免启动错误，实际使用时会从数据库获取
      api-key: ${AI_DASHSCOPE_API_KEY:sk-temp-key-for-startup}
    openai:
      # 提供一个临时的API key来避免启动错误，实际使用时会从数据库获取
      api-key: ${OPENAI_API_KEY:sk-temp-key-for-startup}
    chat:
      memory:
        repository:
          jdbc:
            # 自动初始化数据库表结构
            initialize-schema: always

# Logging Configuration
logging:
  level:
    com.alibaba.cloud.ai.copilot: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  # 工作目录配置
  workspace:
    # 使用 ${file.separator} 或让 Java 代码处理路径拼接
    root-directory: ${user.dir}/workspace  # 改为使用正斜杠，Java会自动转换
    max-file-size: 10485760  # 10MB
    allowed-extensions:
      - .txt
      - .md
      - .java
      - .js
      - .ts
      - .json
      - .xml
      - .yml
      - .yaml
      - .properties
      - .html
      - .css
      - .sql

  # 安全配置
  security:
    approval-mode: DEFAULT  # DEFAULT, AUTO_EDIT, YOLO
    dangerous-commands:
      - rm
      - del
      - format
      - fdisk
      - mkfs

  # 工具配置
  tools:
    read-file:
      enabled: true
      max-lines-per-read: 1000
    write-file:
      enabled: true
      backup-enabled: true
    edit-file:
      enabled: true
      diff-context-lines: 3
    list-directory:
      enabled: true
      max-depth: 5
    shell:
      enabled: true
      timeout-seconds: 30

  # RAG配置
  rag:
    file-upload:
      storage-root: ./data/rag/files
      max-file-size: 10485760  # 10MB
      supported-types:
        - pdf
        - docx
        - doc
        - txt
        - md
        - html
        - rtf
      enable-deduplication: true
    document-processing:
      default-chunk-size: 500
      default-chunk-overlap: 50
      enable-async-processing: true
      processing-timeout-seconds: 300
    vectorization:
      default-embedding-model: text-embedding-v3
      embedding-dimension: 1536
      batch-size: 100
    retrieval:
      default-top-k: 5
      max-top-k: 20
      similarity-threshold: 0.7
      enable-reranking: false
