# RAG模块配置文件
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      embedding:
        options:
          model: text-embedding-ada-002

# RAG模块配置
copilot:
  rag:
    # 文件上传配置
    file-upload:
      storage-root: ./data/rag/files
      max-file-size: 10485760  # 10MB
      supported-types:
        - pdf
        - docx
        - doc
        - txt
        - md
        - html
        - rtf
      enable-deduplication: true
    
    # 文档处理配置
    document-processing:
      chunk-size: 500
      chunk-overlap: 50
      max-tokens-per-chunk: 512
      overlap-tokens: 50
      enable-async-processing: true
      processing-timeout-seconds: 300
    
    # 向量化配置
    vectorization:
      default-embedding-model: text-embedding-ada-002
      embedding-dimension: 1536
      batch-size: 100
    
    # 检索配置
    retrieval:
      default-top-k: 5
      max-top-k: 20
      similarity-threshold: 0.7
      enable-reranking: false
    
    # Embedding模型配置
    embedding:
      provider: openai
      model: text-embedding-ada-002
      timeout: 60
      max-retries: 3
    
    # PgVector向量库配置
    pgvector:
      host: ${PGVECTOR_HOST:localhost}
      port: ${PGVECTOR_PORT:5432}
      database: ${PGVECTOR_DATABASE:copilot_rag}
      username: ${PGVECTOR_USERNAME:postgres}
      password: ${PGVECTOR_PASSWORD:password}
      table: copilot_embeddings
      dimension: 1536

    # 向量存储配置
    vector-store:
      provider: pgvector
      initialize-on-startup: true
      connection-pool-size: 10

# 日志配置
logging:
  level:
    com.alibaba.cloud.ai.copilot.rag: DEBUG
    dev.langchain4j: INFO
    org.springframework.ai: INFO
